### PR TITLE
Display emails in popup

### PR DESCRIPTION
**Pull request by wagnermaciel**

### CODE REVIEW

**Comment by css459** [comment]
Let's merge this once the copy button works. Otherwise it looks great to me! I like the ability to edit the email before copying as well.

**Comment by wagnermaciel** [comment]
@css459 Finished the copy logic. Let me know what you think

**Comment by css459** [comment]
Looks great, works well! I added some file headers and changed the indentation to 4-spaces, plus removed some trailing whitespace. Let me know what you think.

**Comment by wagnermaciel** [comment]
@yc2311 Could you review the changes in this PR to make sure they line up with the style guide you added? If not, we can just go over the major rules of the style guide in person

**Pull request closed without merging**
